[package]
name = "zerocopy-audit-common"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = { version = "^0.1.1", optional = true }
aya = { version = ">=0.11", optional = true }

[features]
user = ["aya"]
bpf = ["aya-ebpf"]
